version: "3"
services:
  db:
    container_name: h2
    image: oscarfonts/h2:1.4.199
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goorm_spring_app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_INITIALIZATION_MODE : always
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/test
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - db